version: '3'

services:
  shipwars-streams:
    container_name: shipwars-streams
    depends_on:
      - shipwars-game-server
    image: quay.io/evanshortiss/shipwars-streams-shot-distribution:latest
    environment:
      QUARKUS_HTTP_PORT: 8585
      # These must be set in your environment when running docker-compose up
      QUARKUS_KAFKA_STREAMS_BOOTSTRAP_SERVERS: "${KAFKACONNECTION_BOOTSTRAPSERVERS}"
      KAFKA_BOOTSTRAP_SERVERS: "${KAFKACONNECTION_BOOTSTRAPSERVERS}"
      KAFKA_CLIENT_ID: "${KAFKACONNECTION_USER}"
      KAFKA_CLIENT_SECRET: "${KAFKACONNECTION_PASSWORD}"
    ports:
      - 8585:8585/tcp
    restart: unless-stopped

  shipwars-client:
    container_name: shipwars-client
    image: quay.io/evanshortiss/shipwars-client:latest
    depends_on:
      - shipwars-game-server
    ports:
      - 8484:8484/tcp
    restart: unless-stopped

  shipwars-game-server:
    container_name: shipwars-game-server
    image: quay.io/evanshortiss/shipwars-game-server:latest
    depends_on:
      - shipwars-bot-server
    ports:
      - 8181:8181/tcp
    environment:
      HTTP_PORT: 8181
      LOG_LEVEL: debug
      NODE_ENV: prod
      HUSKY_SKIP_HOOKS: 1
      AI_AGENT_SERVER_URL: http://shipwars-bot-server:8282
      CLUSTER_NAME: Docker
      # These must be set in your environment when running docker-compose up
      KAFKACONNECTION_BOOTSTRAPSERVERS: "${KAFKACONNECTION_BOOTSTRAPSERVERS}"
      KAFKACONNECTION_SSL: "${KAFKACONNECTION_SSL}"
      KAFKACONNECTION_USER: "${KAFKACONNECTION_USER}"
      KAFKACONNECTION_PASSWORD: "${KAFKACONNECTION_PASSWORD}"
    restart: unless-stopped

  shipwars-bot-server:
    container_name: shipwars-bot-server
    image: quay.io/evanshortiss/shipwars-bot-server:latest
    ports:
      - 8282:8282/tcp
    environment:
      HTTP_PORT: 8282
      NODE_ENV: prod
      HUSKY_SKIP_HOOKS: 1
      AI_SERVER_URL: http://shipwars-move-server:8080/
    restart: unless-stopped

  shipwars-move-server:
    container_name: shipwars-move-server
    image: quay.io/evanshortiss/shipwars-move-server:latest
    ports:
      - 8080:8080/tcp
    restart: unless-stopped
