apiVersion: v1
kind: Template

metadata:
  name: shipwars-game-server

parameters:
  - name: CONFIG_MAP_NAME
    required: true
  - name: NAMESPACE
    required: true

objects:
  - kind: Deployment
    apiVersion: apps/v1
    metadata:
      annotations:
        app.openshift.io/connects-to: >-
          [{"apiVersion":"apps.openshift.io/v1","kind":"DeploymentConfig","name":"shipwars-move-server"}]
      name: shipwars-game-server
      namespace: ${NAMESPACE}
      labels:
        app: shipwars-game-server
        app.kubernetes.io/component: shipwars-game-server
        app.kubernetes.io/instance: shipwars-game-server
        app.kubernetes.io/part-of: shipwars-game
        app.openshift.io/runtime: nodejs
        app.openshift.io/runtime-namespace: ${NAMESPACE}
    spec:
      replicas: 1
      selector:
        matchLabels:
          app: shipwars-game-server
      template:
        metadata:
          creationTimestamp: null
          labels:
            app: shipwars-game-server
            deploymentconfig: shipwars-game-server
        spec:
          containers:
            - name: shipwars-game-server
              image: quay.io/evanshortiss/shipwars-game-server:latest
              ports:
                - containerPort: 8080
                  protocol: TCP
              envFrom:
                - configMapRef:
                    name: shipwars-shared-config
              resources:
                limits:
                  cpu: 250m
                  memory: 256Mi
                requests:
                  cpu: 150m
                  memory: 256Mi
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              imagePullPolicy: Always
          restartPolicy: Always
          terminationGracePeriodSeconds: 30
          dnsPolicy: ClusterFirst
      strategy:
        type: RollingUpdate
        rollingUpdate:
          maxUnavailable: 25%
          maxSurge: 25%
      revisionHistoryLimit: 10
      progressDeadlineSeconds: 600

  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        app.openshift.io/connects-to: '[{"apiVersion":"apps.openshift.io/v1","kind":"DeploymentConfig","name":"shipwars-bot-server"}]'
      labels:
        app: shipwars-game-server
        app.kubernetes.io/component: shipwars-game-server
        app.kubernetes.io/instance: shipwars-game-server
        app.kubernetes.io/part-of: shipwars-game
        app.openshift.io/runtime-version: latest
      name: shipwars-game-server
      namespace: ${NAMESPACE}
    spec:
      ports:
      - name: 8080-tcp
        port: 8080
        protocol: TCP
        targetPort: 8080
      selector:
        app: shipwars-game-server
        deploymentconfig: shipwars-game-server
      sessionAffinity: None
      type: ClusterIP

  - apiVersion: route.openshift.io/v1
    kind: Route
    metadata:
      annotations:
        app.openshift.io/connects-to: '[{"apiVersion":"apps.openshift.io/v1","kind":"DeploymentConfig","name":"shipwars-bot-server"}]'
      labels:
        app: shipwars-game-server
        app.kubernetes.io/component: shipwars-game-server
        app.kubernetes.io/instance: shipwars-game-server
        app.kubernetes.io/part-of: shipwars-game
        app.openshift.io/runtime-version: latest
      name: shipwars-game-server
      namespace: ${NAMESPACE}
    spec:
      path: /shipwars
      port:
        targetPort: 8080-tcp
      tls:
        insecureEdgeTerminationPolicy: Redirect
        termination: edge
      to:
        kind: Service
        name: shipwars-game-server
        weight: 100
      wildcardPolicy: None
